[project]
name = "minimatic"
version = "0.1.0"
description = "An experiment on language design and system integration. VM + DB + Server + Prelude"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "expression>=5.6.0",
]
